### PR TITLE
Fix for issue #76

### PR DESCRIPTION
**Pull request by jimnicholls**
As per issue #76, added JSONWriter, TextWriter and XMLWriter.

JSONWriter and XMLWriter *require* that close() be called in order to close off the JSON array and XML collection element respectively. Because of this, electing to not call close() when using StringIO or BytesIO is not an option.

To support using StringIO and BytesIO, I added an optional `own_file_handle` keyword argument to `__init__` of the writers. When `own_file_handle` is True (the default), calling close() on a writer will also close the file handle. When `own_file_handle` is false, calling close() only closes off the writer and not also the file handle.

The previously documented technique of not calling close() on a MARCWriter when using StringIO still works.

The is some inconsistency with these writers when used with Python 3. MARCWriter and XMLWriter write binary bytes, JSONWriter and TextWriter write unicode characters.

### CODE REVIEW

**Comment by edsu** [comment]
This all looks good! But I'm still a bit confused about why `own_file_handle` is needed. Are there situations when then the underlying filehandle cannot be closed?

**Comment by jimnicholls** [comment]
If we want to write not into a file but into a string using StringIO or into a bytes using BytesIO, then the writer cannot close the file handle because we cannot access the string or bytes after a StringIO or BytesIO is closed.

This does not work:
```python
>>> file_handle = StringIO()
>>> writer = TextWriter(file_handle)
>>> writer.write(Record())
>>> writer.close()  # file_handle is also closed here
>>> print(file_handle.getvalue())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file
```

This does work:
```python
>>> file_handle = StringIO()
>>> writer = TextWriter(file_handle, own_file_handle=False)
>>> writer.write(Record())
>>> writer.close()  # file_handle is not closed here
>>> print(file_handle.getvalue())
=LDR            22        4500
```

**Comment by edsu** [comment]
Ok, thanks! What do you think about making this an option for close() instead of the constructor?

**Comment by jimnicholls** [comment]
That would work. Now that you mention it, it is really a concern of close(). I was just following the C++ pattern where ownership decisions are made at the point where an object is passed into the possible owner.

Shaking off the C++ straight jacket, how about:

```python
def close(also_close_file_handle=True)
```

**Comment by edsu** [comment]
Thanks!

**Comment by jimnicholls** [comment]
I hadn't actually committed the change yet. The last commit above was just a consequence of synching my branch issue76 with your master.

Release version 3.1.4 has the Writer API with own_file_handle in the constructor.

I have the code for close(auto_close_file_handle) ready. But is it now too late?

**Comment by edsu** [comment]
haha, no it's not too late -- sorry I thought I saw it was committed! Let me know when I can merge it in and I'll send out an update.

**Pull request merged**
