### PR TITLE
Mutable leader

### PR DESCRIPTION
**Pull request by herrboyer**
Here's the follow up to https://github.com/edsu/pymarc/issues/108.

Almost nothing was broken after replacing the leader value in `Record` from a string to this `Leader` object except serialization.

### CODE REVIEW

**Comment by edsu** [comment]
@herrboyer did you see the test failure under python2? I didn't take a close look, but will this PR require Python3?

**Comment by herrboyer** [comment]
No @edsu I don't think this PR requires py3 but I had to fix a few things to make it compatible with py2, should be good now !

**Comment by Wooble** [comment]
To be honest if we're going to make a backwards-incompatible major release after the py2 EOL, dropping py2 support seems pretty reasonable...

**Comment by herrboyer** [comment]
@Wooble thanks, I fixed the missing new line and another linting error.

**Pull request merged**
