### PR TITLE
Fix for issue #77

### PR DESCRIPTION
**Pull request by jimnicholls**
As per issue #77, adds an optional leader keyword argument to `__init__` of Record.
Added tests to confirm existing behaviour is maintained, for backwards compatibility.
Tested with Python 2.7.10 and 3.4.3.

### CODE REVIEW

**Comment by jimnicholls** [comment]
Tests are failing because the existing test `test_url` in test/reader.py attempts to download http://inkdroid.org/data/marc.dat. This resource doesn't exist anymore.

**Comment by edsu** [comment]
Thanks. Perhaps it is time to remove that test.

**Comment by jimnicholls** [comment]
Tests are green. And it's the correct branch. I think I've got this right now.

**Comment by edsu** [comment]
Thanks!

**Pull request merged**
